name: Deploy to GitHub Pages

on:
  push:
    branches:
      - deploy

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: deploy

    - name: Copy files to gh-pages branch
      run: |
        git checkout gh-pages
        git pull origin gh-pages
        git checkout deploy -- .
        git commit -m "Update gh-pages branch"
        git push origin gh-pages
